# Generated by Django 2.2.3 on 2020-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/img'),
        ),
    ]
