# Generated by Django 2.2.3 on 2020-10-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20201019_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
